-- O catálogo da matriz de habilidades sai do código e vira cadastro do coordenador.
-- Equipamentos e habilidades entram com o mesmo id que as marcações e notas já usavam
-- (chave do equipamento e H1…H222), então nada do que está gravado muda.

CREATE TABLE "MatrixEquipment" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "archived" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "MatrixEquipment_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "MatrixEquipment_name_key" ON "MatrixEquipment"("name");

CREATE TABLE "MatrixSkill" (
    "id" TEXT NOT NULL,
    "equipmentId" TEXT NOT NULL,
    "subgroup" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "level" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "archived" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "MatrixSkill_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "MatrixSkill_equipmentId_idx" ON "MatrixSkill"("equipmentId");

ALTER TABLE "MatrixSkill" ADD CONSTRAINT "MatrixSkill_equipmentId_fkey" FOREIGN KEY ("equipmentId") REFERENCES "MatrixEquipment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO "MatrixEquipment" ("id", "name", "position") VALUES
  ('blistadeira-cam', 'Blistadeira CAM', 1),
  ('encartuchadeira-cam', 'Encartuchadeira CAM', 2),
  ('encaixotadora-cam', 'Encaixotadora CAM', 3),
  ('blistadeira-uhlmann', 'Blistadeira Uhlmann', 4),
  ('encartuchadeira-uhlmann', 'Encartuchadeira Uhlmann', 5),
  ('encaixotadora-uhlmann', 'Encaixotadora Uhlmann', 6),
  ('blistadeira-mediseal', 'Blistadeira Mediseal', 7),
  ('encartuchadeira-mediseal', 'Encartuchadeira Mediseal', 8),
  ('encaixotadora-mediseal', 'Encaixotadora Mediseal', 9);

INSERT INTO "MatrixSkill" ("id", "equipmentId", "subgroup", "text", "level", "position") VALUES
  ('H1', 'blistadeira-cam', 'Desbobinador', 'Identificar elementos de apoio do porta bobina e sua funcionalidade.', 'basic', 1),
  ('H2', 'blistadeira-cam', 'Desbobinador', 'Conhecimento em fixação dos roldanas de alinhamento do material', 'basic', 2),
  ('H3', 'blistadeira-cam', 'Desbobinador', 'Análise do circuito dos rolos de passagem quanto a travamento mecânico', 'basic', 3),
  ('H4', 'blistadeira-cam', 'Desbobinador', 'Conhecimento em análise de folgas mecânicas no conjunto de tração', 'basic', 4),
  ('H5', 'blistadeira-cam', 'Desbobinador', 'Análise do correto funcionamento do balancin de tensionamento do material', 'intermediate', 5),
  ('H6', 'blistadeira-cam', 'Desbobinador', 'Ajuste em alinhamento do desbobinamento', 'intermediate', 6),
  ('H7', 'blistadeira-cam', 'Placa de Aquecimento', 'Identificação de folgas nos eixos e guias', 'basic', 7),
  ('H8', 'blistadeira-cam', 'Placa de Aquecimento', 'Ajuste de alinhamento entre as placas superior e inferior', 'advanced', 8),
  ('H9', 'blistadeira-cam', 'Placa de Aquecimento', 'limpeza das placas superiores e inferiores', 'basic', 9),
  ('H10', 'blistadeira-cam', 'Estampo de Formação', 'Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica', 'advanced', 10),
  ('H11', 'blistadeira-cam', 'Estampo de Formação', 'Conferencia ponto zero mecânico da formação', 'intermediate', 11),
  ('H12', 'blistadeira-cam', 'Estampo de Formação', 'Revisão do conjunto das molas prato', 'advanced', 12),
  ('H13', 'blistadeira-cam', 'Estampo de Formação', 'Verificar o correto funcionamento do mecanismo de movimentação do pré formador', 'advanced', 13),
  ('H14', 'blistadeira-cam', 'Primeira Pinça', 'Verificar o correto funcionamento do mecanismo da pinça, se o sistema de catraca (Rolamento contra recúo) está ok, verificar a pressão do contra rolo e condição das correias', 'advanced', 14),
  ('H15', 'blistadeira-cam', 'Segunda Pinça', 'Identificação de folgas em eixos, rolamentos lineares, travamento da pinça, rotulas e no sistema de puxada (glifo)', 'intermediate', 15),
  ('H16', 'blistadeira-cam', 'Segunda Pinça', 'Revisão do sistema Glifo', 'advanced', 16),
  ('H17', 'blistadeira-cam', 'Mesa de Alimentação', 'Identificação de folgas em eixos, rolamentos lineares, rotulas e no sistema de puxada (glifo)', 'intermediate', 17),
  ('H18', 'blistadeira-cam', 'Mesa de Alimentação', 'Ajuste de passo mecânico', 'advanced', 18),
  ('H19', 'blistadeira-cam', 'Porta Bobina de material de selagem', 'Verificar o correto funcionamento do porta bobina e dos rolos de passagem E balancim', 'basic', 19),
  ('H20', 'blistadeira-cam', 'Estação de Selagem', 'Revisão completa do conjunto de selagem', 'advanced', 20),
  ('H21', 'blistadeira-cam', 'Estação de Selagem', 'Revisão do multiplicador de pressão', 'advanced', 21),
  ('H22', 'blistadeira-cam', 'Estação de Selagem', 'Identificação de folgas mecânicas no conjunto de transmissão da selagem inferior e superior e verificação do ponto zero mecânico', 'advanced', 22),
  ('H23', 'blistadeira-cam', 'Estação de Selagem', 'Verificar folgas nas guias de fixação das ferramentas de selagem inferior e superior', 'intermediate', 23),
  ('H24', 'blistadeira-cam', 'Estação de Selagem', 'Verificar correto funcionamento do sistema hidropneumático e se existe indícios de vazamento de óleo', 'advanced', 24),
  ('H25', 'blistadeira-cam', 'Estação de Refrigeração selagem', 'Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica', 'intermediate', 25),
  ('H26', 'blistadeira-cam', 'Terceira Pinça', 'Identificação de folgas em eixos, rolamentos lineares, travamento da pinça, rotulas e no sistema de puxada (glifo)', 'intermediate', 26),
  ('H27', 'blistadeira-cam', 'Quarta Pinça', 'Conhecimento em sistema mecânico para identificação de folgas em eixos, rolamentos lineares e desgaste na placa superior de apoio da manta', 'intermediate', 27),
  ('H28', 'blistadeira-cam', 'Estação de Corte', 'Revisão do sistema de corte e identificação do ponto zero mecânico', 'advanced', 28),
  ('H29', 'blistadeira-cam', 'Transferência de Blister', 'Verificar folgas no conjunto mecânico do porta ventosa, funcionamento do vácuo e identificação do ponto mecânico', 'advanced', 29),
  ('H30', 'blistadeira-cam', 'Transferência de Blister', 'Revisão completa do conjunto da esteira de saída.', 'intermediate', 30),
  ('H31', 'blistadeira-cam', 'Transferência de Blister', 'Revisão completa do conjunto do acelerador de blister.', 'intermediate', 31),
  ('H32', 'blistadeira-cam', 'Sist. de Transmissão Principal', 'Revisão completa do redutor de transmissão principal', 'advanced', 32),
  ('H33', 'blistadeira-cam', 'Sist. de Transmissão Principal', 'Verificação do conjunto de transmissão quanto a folgas no redutor, entre redutor e eixo principal, desgastes de correntes e coroas.', 'intermediate', 33),
  ('H34', 'blistadeira-cam', 'Sist. de Transmissão Principal', 'Realizar o alinhamento de transmissão por corrente, polia/correia e desgastes mecânicos', 'intermediate', 34),
  ('H35', 'blistadeira-cam', 'Sist. de Transmissão Principal', 'Conhecimento em ajuste do freio motor conforme manual do fabricante', 'intermediate', 35),
  ('H36', 'blistadeira-cam', 'Sist. de Transmissão Principal', 'Verificação do ponto zero mecânico com eletrônico da máquina', 'advanced', 36),
  ('H37', 'blistadeira-cam', 'Lubrificação', 'Lubrificação Geral', 'basic', 37),
  ('H38', 'encartuchadeira-cam', 'Magazine de Blister', 'Ajuste e calibração das garrinhas de seleção de blister, e revisão completa dos sub conjuntos.', 'advanced', 1),
  ('H39', 'encartuchadeira-cam', 'Esteira Transporte de Blister', 'Identificação de folgas no sistema de transmissão por corrente, identificação de tensionamento e desgastes da corrente, verificar se existem folgas mecânicas no conjunto carrinhos e eixos', 'advanced', 2),
  ('H40', 'encartuchadeira-cam', 'Esteira Transporte de Blister', 'Lubrificação e limpeza dos conjunto', 'basic', 3),
  ('H41', 'encartuchadeira-cam', 'GUK', 'Revisão geral do guk', 'advanced', 4),
  ('H42', 'encartuchadeira-cam', 'GUK', 'Verificar se há folgas no sistema de transmissão por eixos e engrenagens e servo acionamento. Identificar o ponto zero mecânico do GUK.', 'advanced', 5),
  ('H43', 'encartuchadeira-cam', 'GUK', 'Realizar limpeza e lubrificação', 'basic', 6),
  ('H44', 'encartuchadeira-cam', 'GUK', 'Verificação de folgas ou excesso de pressão entre rolos de dobra de bula e identificação de desgaste da borracha e recartilho do rolo.', 'advanced', 7),
  ('H45', 'encartuchadeira-cam', 'GUK', 'Verificar sistema de vácuo se existem possíveis ponto de perda de vácuo e identificação do ponto mecânico de acionamento do vácuo.', 'advanced', 8),
  ('H46', 'encartuchadeira-cam', 'Magazine de Cartucho', 'Verificar o correto funcionamento do sistema de transporte de cartucho por esteira sincronizada e se existem folgas no sistema de acionamento', 'intermediate', 9),
  ('H47', 'encartuchadeira-cam', 'Armação de Cartucho', 'Revisão completa do eixo vertical', 'advanced', 10),
  ('H48', 'encartuchadeira-cam', 'Armação de Cartucho', 'Revisar conjunto do cicloide de armação de cartucho', 'advanced', 11),
  ('H49', 'encartuchadeira-cam', 'Armação de Cartucho', 'Verificar a eficiência do sistema de vácuo e se as válvulas de abertura e fechamento de vácuo estão funcionando corretamente', 'advanced', 12),
  ('H50', 'encartuchadeira-cam', 'Armação de Cartucho', 'Revisar sistema de transmissão por eixos e engrenagens e correia sincronizada', 'advanced', 13),
  ('H51', 'encartuchadeira-cam', 'Armação de Cartucho', 'Verificar o correto alinhamento e funcionamento dos braços de retirada de cartucho', 'intermediate', 14),
  ('H52', 'encartuchadeira-cam', 'Introdução de Blister', 'Revisão completa do conjunto de empurradores', 'advanced', 15),
  ('H53', 'encartuchadeira-cam', 'Introdução de Blister', 'Verificar se existem folgas mecânicas nas correntes de transmissão, eixos, buchas e carrinhos dos empurradores e verificar o correto sincronismo com as canecas', 'advanced', 16),
  ('H54', 'encartuchadeira-cam', 'Introdução de Blister', 'Verificar possíveis folgas e desalinhamento das guias de avanço e retorno dos empurradores', 'advanced', 17),
  ('H55', 'encartuchadeira-cam', 'Introdução de Blister', 'Realizar a correta limpeza e lubrificação dos eixos, guias e correntes', 'basic', 18),
  ('H56', 'encartuchadeira-cam', 'Hotmelt', 'Verificar correto funcionamento dos bicos de cola quanto a vazamentos, identificação residuos de cola nas guias de fechamento e ajuste de vazão de cola e pressão pneumática dos módulos e bomba', 'intermediate', 19),
  ('H57', 'encartuchadeira-cam', 'Sistema de fechamento de cartucho', 'Verificar guias de montagem do cartucho, pinça do fechamento de abas e guias de fechamento de abas.', 'intermediate', 20),
  ('H58', 'encartuchadeira-cam', 'Sistema de transporte de cartuchos', 'Revisão completa do conjunto de transmissão', 'advanced', 21),
  ('H59', 'encartuchadeira-cam', 'Esteira de Saída', 'Revisão do rolo do conjunto de transmissão da esteira de saída', 'intermediate', 22),
  ('H60', 'encartuchadeira-cam', 'Esteira de Saída', 'Verificação de alinhamento das correias e possíveis folgas no conjunto de transmissão mecânica dos rolos', 'intermediate', 23),
  ('H61', 'encartuchadeira-cam', 'Esteira de Saída', 'Lubrificação e limpeza dos conjunto', 'basic', 24),
  ('H62', 'encartuchadeira-cam', 'Sist. de Transmissão Principal', 'Alinhamento de transmissão por corrente, polia/correia e desgastes mecânicos', 'advanced', 25),
  ('H63', 'encartuchadeira-cam', 'Sist. de Transmissão Principal', 'Conhecimento em ajuste do freio motor conforme manual do fabricante', 'advanced', 26),
  ('H64', 'encartuchadeira-cam', 'Sist. de Transmissão Principal', 'Verificação do ponto zero mecânico com eletrônico da máquina com verificação dos segintes conjuntos: ciclóide, transporte de canecas, engrenagens do sistema de fechamento nos lados dianteiros e traseiro', 'advanced', 27),
  ('H65', 'encartuchadeira-cam', 'Transporte de canecas', 'Revisão completa do conjunto de carrinho e caneca', 'advanced', 28),
  ('H66', 'encartuchadeira-cam', 'Transporte de canecas', 'Regulagem do tencionamento da corrente com o sensor (Alarme S 27)', 'intermediate', 29),
  ('H67', 'encartuchadeira-cam', 'Lubrificação', 'Limpeza e lubrificação Geral', 'basic', 30),
  ('H68', 'encartuchadeira-cam', 'Balança', 'Verificação das condições das esteiras de entrada, pesagem e saída, alinhamento e tensionamento e desgastes da correia sincronizada, verificação os rolamentos dos rolos', 'intermediate', 31),
  ('H69', 'encaixotadora-cam', 'Esteira de entrada', 'Revisão completa do conjunto da esteira de entrada.', 'intermediate', 1),
  ('H70', 'encaixotadora-cam', 'Empilhador', 'Verificar se está realizando o correto empilhamento, se o sistema de elevação e contra elevação estão funcionando corretamente', 'intermediate', 2),
  ('H71', 'encaixotadora-cam', 'Armação de Caixas', 'Verificar correto funcionamento do sistema de vácuo e sua eficiência.', 'intermediate', 3),
  ('H72', 'encaixotadora-cam', 'Armação de Caixas', 'Verificar o correto funcionamento do mecanismo de montagem e alinhamento de caixa', 'intermediate', 4),
  ('H73', 'encaixotadora-cam', 'Armação de Caixas', 'Revisão do sistema de transmissão de armação (redutor, came e eixo)', 'advanced', 5),
  ('H74', 'encaixotadora-cam', 'Empurradores', 'Verificação da eficiência da transferencia dos cartuchos e o correto ajuste de entrodução dos cartuchos na caixa de embarque.', 'intermediate', 6),
  ('H75', 'encaixotadora-cam', 'Fechamento de Caixas', 'Verificar o correto funcionamento das esterias de transporte da caixa de embarque, desgaste e folga mecânica nos rolos de transporte. Verificar o correto ajuste nas guias de dobramento das abas. Verificar a correta aplicação da fita de fechamento.', 'intermediate', 7),
  ('H76', 'encaixotadora-cam', 'Sist. de Transmissão Principal', 'Verificação do ponto zero mecânico com eletrônico da máquina.', 'advanced', 8),
  ('H77', 'encaixotadora-cam', 'Lubrificação', 'Limpeza e lubrificação Geral', 'basic', 9),
  ('H78', 'blistadeira-uhlmann', 'Desbobinador', 'Verificar elementos de apoio do porta bobinas (Freios porta bobina, eixos infláveis, proteções) se estão funcionando corretamente.', 'basic', 1),
  ('H79', 'blistadeira-uhlmann', 'Desbobinador', 'Realizar calibração do sistema automático de centralização da manta.', 'advanced', 2),
  ('H80', 'blistadeira-uhlmann', 'Desbobinador', 'Realizar centralização manual da manta no desbobinador.', 'intermediate', 3),
  ('H81', 'blistadeira-uhlmann', 'Desbobinador', 'Revisão geral dos rolos de passagem do desbobinador.', 'basic', 4),
  ('H82', 'blistadeira-uhlmann', 'Desbobinador', 'Realizar ajuste correto do pulmão.', 'basic', 5),
  ('H83', 'blistadeira-uhlmann', 'Placa de Aquecimento', 'Identificação de folgas mecânicas e eletrônicos no conjunto de movimentação das placas de aquecimento Inferior e superior (Terminais de rotula e guias lineares).', 'intermediate', 6),
  ('H84', 'blistadeira-uhlmann', 'Placa de Aquecimento', 'Ajuste de alinhamento entre as placas superior e inferior e limpeza.', 'advanced', 7),
  ('H85', 'blistadeira-uhlmann', 'Placa de Aquecimento', 'Verificar funcionamento do stop das placas de aquecimento.', 'intermediate', 8),
  ('H86', 'blistadeira-uhlmann', 'Estampo de Formação', 'Troca e calibração do conjunto de mola pratos.', 'advanced', 9),
  ('H87', 'blistadeira-uhlmann', 'Estampo de Formação', 'Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica e vazamentos.', 'basic', 10),
  ('H88', 'blistadeira-uhlmann', 'Estampo de Formação', 'Conferência ponto zero mecânico da formação via interface IHM.', 'advanced', 11),
  ('H89', 'blistadeira-uhlmann', 'Estampo de Formação', 'Verificar folgas ou desgastes no sistema de trava da ferramenta superior e inferior.', 'basic', 12),
  ('H90', 'blistadeira-uhlmann', 'Estampo de Formação', 'Verificar funcionamento e se existe vazamento das vávulas de entrada e saída de ar de formação.', 'intermediate', 13),
  ('H91', 'blistadeira-uhlmann', 'Pinça de Puxada pós Formação', 'Verificar o correto funcionamento do acionamento da pinça. Verificar o desgaste e a calibração dos batoques de travamento da pinça e verificar a movimentação mecânica de puxada da manta.', 'intermediate', 14),
  ('H92', 'blistadeira-uhlmann', 'Balacin de Controle da Manta', 'Verificar o correto zeramento do encoder.', 'advanced', 15),
  ('H93', 'blistadeira-uhlmann', 'Mesa de Alimentação', 'Revisão geral do conjunto da escova transversal e mescladores.', 'intermediate', 16),
  ('H94', 'blistadeira-uhlmann', 'Mesa de Alimentação', 'Revisão geral do conjunto alimentador Simtap', 'intermediate', 17),
  ('H95', 'blistadeira-uhlmann', 'Mesa de Alimentação', 'Verificar correto funcionamento da calha de alimentação.', 'intermediate', 18),
  ('H96', 'blistadeira-uhlmann', 'Porta Bobina de material de selagem', 'Verificar o correto funcionamento do porta bobina e dos rolos de passagem , incluindo os rolos do TIJ.', 'intermediate', 19),
  ('H97', 'blistadeira-uhlmann', 'Estação de Selagem', 'Revisão geral do conjunto do rolo de selagem (com apoio do eletricista).', 'intermediate', 20),
  ('H98', 'blistadeira-uhlmann', 'Estação de Selagem', 'Verificar folgas ou desgastes no sistema da trava do rolo da ferramenta de selagem.', 'basic', 21),
  ('H99', 'blistadeira-uhlmann', 'Estação de Selagem', 'Verificar correto funcionamento do sistema pneumático de acionamento do rolo quente de selagem.', 'basic', 22),
  ('H100', 'blistadeira-uhlmann', 'Estação de Refrigeração no Rolo de Selagem', 'Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica e vazamentos.', 'intermediate', 23),
  ('H101', 'blistadeira-uhlmann', 'Rolo de Puxada do Filme', 'Verificar possiveis desgastes no rolo, possiveis desalinhamentos entre os extremos do rolo, folga nos rolamentos e o correto travamento da manta após o fechamento do rolo movél.', 'intermediate', 24),
  ('H102', 'blistadeira-uhlmann', 'Estação de Corte', 'Verificar possíveis folgas no conjunto de movimento do corte, verificar se a contra-faca está cortando com eficiência o retalho do blister.', 'advanced', 25),
  ('H103', 'blistadeira-uhlmann', 'Transferência de Blister', 'Verificar o alinhamento do porta ventosa, verificar o sincronismo de entrega de blisters com a esteira de transferência, verificar a eficiência do vácuo da PIAB.', 'advanced', 26),
  ('H104', 'blistadeira-uhlmann', 'Transferência de Blister', 'Verificar o tensionamento e alinhamento das esteiras de transporte de blisters, verificar se há desgaste internamente nas esteiras, verificar se há existem desagastes nas abas das polias próximo ao porta ventosa, verificar a eficiência de vácuo nas esteiras e realizar a troca das esteiras.', 'intermediate', 27),
  ('H105', 'blistadeira-uhlmann', 'Transferência de Blister', 'Verificar o correto funcionamento dos batedores e dos stops de blisters. Realizar revisão e limpeza.', 'intermediate', 28),
  ('H106', 'blistadeira-uhlmann', 'Sist. de Transmissão Geral', 'Revisão dos redutores planetários.', 'basic', 29),
  ('H107', 'blistadeira-uhlmann', 'Lubrificação', 'Limpeza e lubrificação Geral', 'basic', 30),
  ('H108', 'encartuchadeira-uhlmann', 'Magazine de Blister', 'Ajuste e calibração dos discos de seleção de blister, servo de acionamento e folgas no conjunto mecânico. Verificação do ponto de entrega de blister na esteira.', 'basic', 1),
  ('H109', 'encartuchadeira-uhlmann', 'Esteira Transporte de Blister', 'Verificar o correto funcionamento da esteira', 'intermediate', 2),
  ('H110', 'encartuchadeira-uhlmann', 'GUK', 'Verificar se há folgas no sistema de transmissão por eixos e engrenagens e servo acionamento. Identificar o ponto zero mecânico do GUK.', 'advanced', 3),
  ('H111', 'encartuchadeira-uhlmann', 'GUK', 'Realizar limpeza e lubrificação', 'basic', 4),
  ('H112', 'encartuchadeira-uhlmann', 'GUK', 'Verificação de folgas ou excesso de pressão entre rolos de dobra de bula e identificação de desgaste da borracha e recartilho do rolo.', 'intermediate', 5),
  ('H113', 'encartuchadeira-uhlmann', 'GUK', 'Verificar sistema de vácuo se existem possíveis ponto de perda de vácuo e identificação do ponto mecânico de acionamento do vácuo.', 'advanced', 6),
  ('H114', 'encartuchadeira-uhlmann', 'Magazine de Cartucho', 'Verificar o correto funcionamento do sistema de transporte de cartucho por esteira sincronizada e se existem folgas no sistema de acionamento', 'intermediate', 7),
  ('H115', 'encartuchadeira-uhlmann', 'Armação de Cartucho', 'Verificar possíveis folgas no sistema de transmissão por eixos e engrenagens e correia sincronizada', 'advanced', 8),
  ('H116', 'encartuchadeira-uhlmann', 'Armação de Cartucho', 'Verificar o correto alinhamento e funcionamento dos braços de retirada de cartucho', 'intermediate', 9),
  ('H117', 'encartuchadeira-uhlmann', 'Introdução de Blister', 'Verificar se existem folgas mecânicas nas correntes de transmissão, eixos, buchas e carrinhos dos empurradores e verificar o correto sincronismo com os pentes', 'advanced', 10),
  ('H118', 'encartuchadeira-uhlmann', 'Introdução de Blister', 'Verificar possíveis folgas e desalinhamento das guias de avanço e retorno dos empurradores', 'intermediate', 11),
  ('H119', 'encartuchadeira-uhlmann', 'Introdução de Blister', 'Realizar a correta limpeza e lubrificação dos eixos, guias e correntes', 'basic', 12),
  ('H120', 'encartuchadeira-uhlmann', 'Empurradores', 'Verificar o correto funcionamento do conjunto de empurradores', 'advanced', 13),
  ('H121', 'encartuchadeira-uhlmann', 'HotMelt', 'Verificar correto funcionamento dos bicos de cola quanto a vazamentos, identificação residuos de cola nas guias de fechamento e ajuste de vazão de cola e pressão pneumática dos módulos e bomba.', 'intermediate', 14),
  ('H122', 'encartuchadeira-uhlmann', 'Fechamento de cartucho', 'Verificar o correto funcionamento do datador domino', 'basic', 15),
  ('H123', 'encartuchadeira-uhlmann', 'Sistema de fechamento de cartucho', 'Verificar guias de montagem do cartucho, pinça do fechamento de abas e guias de fechamento de abas.', 'intermediate', 16),
  ('H124', 'encartuchadeira-uhlmann', 'Esteira de Saída', 'Verificação de alinhamento das correias e possíveis folgas no conjunto de transmissão mecânica dos rolos', 'intermediate', 17),
  ('H125', 'encartuchadeira-uhlmann', 'Esteira de Saída', 'Lubrificação e limpeza dos conjunto', 'basic', 18),
  ('H126', 'encartuchadeira-uhlmann', 'Sist. de Transmissão Principal', 'Alinhamento de transmissão por corrente, polia/correia e desgastes mecânicos', 'advanced', 19),
  ('H127', 'encartuchadeira-uhlmann', 'Lubrificação', 'Limpeza e lubrificação Geral', 'basic', 20),
  ('H128', 'encartuchadeira-uhlmann', 'Sist. de Transmissão Principal', 'Verificação do ponto zero mecânico com eletrônico da máquina, verificando o zero eletrôncio do encoder com o zero mecânico da maquina.', 'intermediate', 21),
  ('H129', 'encartuchadeira-uhlmann', 'Balança', 'Verificação das condições das esteiras de entrada, pesagem e saída, alinhamento e tensionamento e desgastes da correia sincronizada, verificação os rolamentos dos rolos', 'intermediate', 22),
  ('H130', 'encaixotadora-uhlmann', 'Magazine de Caixas', 'Verificação o correto alinhamento do magazine e se o sistema de reposição de caixas por correia sincronizada está funcionando corretamente', 'advanced', 1),
  ('H131', 'encaixotadora-uhlmann', 'Magazine de Caixas', 'Verificar se está realizando o correto empilhamento, se o sistema de elevação e contra elevação estão funcionando corretamente', 'intermediate', 2),
  ('H132', 'encaixotadora-uhlmann', 'Magazine de Caixas', 'Verificar correto funcionamento do sistema de vácuo e sua eficiência.', 'intermediate', 3),
  ('H133', 'encaixotadora-uhlmann', 'Esteira de entrada', 'Verificar correto funcionamento de tração da esteira se existem folgas mecanicas no conjunto.', 'basic', 4),
  ('H134', 'encaixotadora-uhlmann', 'Empilhador', 'Verificar o correto funcionamento do mecanismo de montagem e alinhamento de caixa', 'intermediate', 5),
  ('H135', 'encaixotadora-uhlmann', 'Armação de Caixas', 'Verificação da eficiência da transferencia dos cartuchos e o correto ajuste de introdução dos cartuchos na caixa de embarque.', 'intermediate', 6),
  ('H136', 'encaixotadora-uhlmann', 'Empurradores', 'Verificar o correto funcionamento das esterias de transporte da caixa de embarque, desgaste e folga mecânica nos rolos de transporte. Verificar o correto ajuste nas guias de dobramento das abas. Verificar a correta aplicação da fita de fechamento.', 'intermediate', 7),
  ('H137', 'encaixotadora-uhlmann', 'Empurradores', 'Verificação do ponto zero mecânico com eletrônico da máquina.', 'intermediate', 8),
  ('H138', 'encaixotadora-uhlmann', 'Sist. de Transmissão Principal', 'Limpeza e lubrificação Geral', 'basic', 9),
  ('H139', 'encaixotadora-uhlmann', 'Sist. de Transmissão Principal', 'Ajuste de parâmetro do formato', 'basic', 10),
  ('H140', 'encaixotadora-uhlmann', 'Sist. de Transmissão Principal', 'Verificar o correto funcionamento do sistema de vácuo', 'basic', 11),
  ('H141', 'blistadeira-mediseal', 'Bistadeira', 'Realizar os zeramentos de todos os pontos de formato da máquina.', 'advanced', 1),
  ('H142', 'blistadeira-mediseal', 'Desbobinador', 'Identificar elementos (carrinho) de apoio do porta bobina e sua funcionalidade.', 'basic', 2),
  ('H143', 'blistadeira-mediseal', 'Desbobinador', 'Revisão conjunto do redutor e acoplamento de tração da bobina', 'intermediate', 3),
  ('H144', 'blistadeira-mediseal', 'Desbobinador', 'Análise do circuito dos rolos de passagem quanto a travamento mecânico', 'basic', 4),
  ('H145', 'blistadeira-mediseal', 'Desbobinador', 'Conhecimento em análise de desgastes mecânicos no rolo de tração da manta.', 'basic', 5),
  ('H146', 'blistadeira-mediseal', 'Placa de Aquecimento', 'Identificação de folgas mecânicas no conjunto de movimentação das placas de aquecimento.', 'intermediate', 6),
  ('H147', 'blistadeira-mediseal', 'Placa de Aquecimento', 'Ajuste e alinhamento das placas do forno.', 'advanced', 7),
  ('H148', 'blistadeira-mediseal', 'Disco de puxada de filme da Formação', 'Verificar possíveis desgaste nos discos e calibração.', 'intermediate', 8),
  ('H149', 'blistadeira-mediseal', 'Estampo de Formação', 'Revisão completa do conjunto da base da placa de formação.', 'advanced', 9),
  ('H150', 'blistadeira-mediseal', 'Estampo de Formação', 'Verificação do ponto zero da formação principal e da formação mecânica.', 'intermediate', 10),
  ('H151', 'blistadeira-mediseal', 'Estampo de Formação', 'Zeramento do reloginho de ajuste do pré punção.', 'intermediate', 11),
  ('H152', 'blistadeira-mediseal', 'Estampo de Formação', 'Limpeza completa do sistema de arrefecimento.', 'intermediate', 12),
  ('H153', 'blistadeira-mediseal', 'Estampo de Formação', 'Conferencia ponto zero mecânico da formação via interface IHM.', 'intermediate', 13),
  ('H154', 'blistadeira-mediseal', 'Estampo de Formação', 'Verificar folgas ou desgastes no sistema de travas das ferramentas, verificar se existem vazamentos de água.', 'intermediate', 14),
  ('H155', 'blistadeira-mediseal', 'Estampo de Formação', 'Revisão do conjunto de molas prato.', 'advanced', 15),
  ('H156', 'blistadeira-mediseal', 'Balacin pós formação', 'Verificar o correto zeramento do encoder.', 'intermediate', 16),
  ('H157', 'blistadeira-mediseal', 'Alimentação', 'Ajuste de vibração do vibrador da calha de alimentação.', 'intermediate', 17),
  ('H158', 'blistadeira-mediseal', 'Porta Bobina de material de selagem', 'Identificar elementos (carrinho) de apoio do porta bobina e sua funcionalidade.', 'basic', 18),
  ('H159', 'blistadeira-mediseal', 'Porta Bobina de material de selagem', 'Análise do correto funcionamento do balancin de tração do material', 'basic', 19),
  ('H160', 'blistadeira-mediseal', 'Porta Bobina de material de selagem', 'Analise de funcionamento do controle de canto do alumínio.', 'intermediate', 20),
  ('H161', 'blistadeira-mediseal', 'Estação de Selagem', 'Revisão no conjunto do rolo quente de selagem.', 'advanced', 21),
  ('H162', 'blistadeira-mediseal', 'Estação de Selagem', 'Verificar folgas ou desgastes no sistema de trava do rolo de selagem.', 'intermediate', 22),
  ('H163', 'blistadeira-mediseal', 'Estação de Selagem', 'Verificar correto funcionamento do sistema pneumático de acionamento do rolo de selagem quente e se existem indícios de desgastes mecânicos.', 'advanced', 23),
  ('H164', 'blistadeira-mediseal', 'Estação de Selagem', 'Verificação do ponto zero mecânico com eletrônico.', 'advanced', 24),
  ('H165', 'blistadeira-mediseal', 'Estação de Selagem', 'Verificação do correto funciomento do trocador de calor da selagem.', 'advanced', 25),
  ('H166', 'blistadeira-mediseal', 'Estação de Refrigeração no Rolo de Selagem', 'Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica e junta rotativa.', 'intermediate', 26),
  ('H167', 'blistadeira-mediseal', 'Balacin de Controle da Manta pós Selagem', 'Verificar o correto zeramento do encoder.', 'advanced', 27),
  ('H168', 'blistadeira-mediseal', 'Disco de Puxada de filme da perfuração', 'Verificar possíveis desgaste nos discos e calibração.', 'intermediate', 28),
  ('H169', 'blistadeira-mediseal', 'disco de puxada do filme de corte', 'Verificar possíveis desgaste nos disco e calibração.', 'intermediate', 29),
  ('H170', 'blistadeira-mediseal', 'Estação de carimbo de blister', 'Revisão do conjunto do carimbo', 'advanced', 30),
  ('H171', 'blistadeira-mediseal', 'Estação de Corte', 'Revisão do conjunto do sistema de corte.', 'advanced', 31),
  ('H172', 'blistadeira-mediseal', 'Transferência de Blister', 'Revisão do cicloide de blister.', 'advanced', 32),
  ('H173', 'blistadeira-mediseal', 'Transferência de Blister', 'Montagem do cicloide de blister no equipamento.', 'advanced', 33),
  ('H174', 'blistadeira-mediseal', 'Transferência de Blister', 'Teste de vazamento entre as câmaras do cicloide.', 'advanced', 34),
  ('H175', 'blistadeira-mediseal', 'Transferência de Blister', 'Verificar ponto zero do sistema de cicloide, faca e carimbo', 'advanced', 35),
  ('H176', 'blistadeira-mediseal', 'Transferência de Blister', 'Revisão da bomba de vácuo.', 'basic', 36),
  ('H177', 'blistadeira-mediseal', 'Transferência de Blister', 'Verificar a eficiência do vácuo da bomba.', 'basic', 37),
  ('H178', 'blistadeira-mediseal', 'Transferência de Blister', 'Verificar o tensionamento e alinhamento das esteiras de transporte de blisters, e ponto zero das esteiras de blisters.', 'intermediate', 38),
  ('H179', 'blistadeira-mediseal', 'Transferência de Blister', 'Revisão completa do trânsferidor de blister e zeramento.', 'intermediate', 39),
  ('H180', 'blistadeira-mediseal', 'Lubrificação', 'Limpeza e lubrificação Geral', 'basic', 40),
  ('H181', 'encartuchadeira-mediseal', 'Compensador de blister', 'Verificar ponto zero mecânico com eletrônico, e revisão mecânica', 'intermediate', 1),
  ('H182', 'encartuchadeira-mediseal', 'Magazine de Blister', 'Verificar ponto zero mecânico com eletrônico, e revisão mecânica', 'intermediate', 2),
  ('H183', 'encartuchadeira-mediseal', 'Esteira Curta e Longa deTransporte de Blister', 'Revisão completa do conjunto (Transporte e Elevação) e verificação do ponto zero mêcanico com eletônico', 'intermediate', 3),
  ('H184', 'encartuchadeira-mediseal', 'GUK', 'Revisão geral do guk', 'advanced', 4),
  ('H185', 'encartuchadeira-mediseal', 'GUK', 'Verificar se há folgas no sistema de transmissão por eixos e engrenagens e servo acionamento. Identificar o ponto zero mecânico do GUK.', 'advanced', 5),
  ('H186', 'encartuchadeira-mediseal', 'GUK', 'Realizar limpeza e lubrificação', 'basic', 6),
  ('H187', 'encartuchadeira-mediseal', 'GUK', 'Verificação de folgas ou excesso de pressão entre rolos de dobra de bula e identificação de desgaste da borracha e recartilho do rolo.', 'advanced', 7),
  ('H188', 'encartuchadeira-mediseal', 'GUK', 'Verificar sistema de vácuo se existem possíveis ponto de perda de vácuo e identificação do ponto mecânico de acionamento do vácuo.', 'advanced', 8),
  ('H189', 'encartuchadeira-mediseal', 'Transporte de bula (Correia)', 'Realizar troca e ajustes das correias de transporte e revisão do conjunto.', 'advanced', 9),
  ('H190', 'encartuchadeira-mediseal', 'Transporte de bula', 'Análise do correto funcionamento dos rolos separadores e stop de bula.', 'advanced', 10),
  ('H191', 'encartuchadeira-mediseal', 'Transporte de bula (Pinças)', 'Realizar revisão das pinças, guias de abertura, troca da correia e verificação do ponto zero mêcanico com eletônico.', 'intermediate', 11),
  ('H192', 'encartuchadeira-mediseal', 'Empilhamento de blister', 'Realizar revisão completa do conjunto em bancada.', 'advanced', 12),
  ('H193', 'encartuchadeira-mediseal', 'Empilhamento de blister', 'Realizar ajuste do empilhador de blisters conforme procedimento, e verificação do ponto zero mêcanico com eletônico', 'advanced', 13),
  ('H194', 'encartuchadeira-mediseal', 'Bascula', 'Realizar revisão completa do conjunto em bancada.', 'intermediate', 14),
  ('H195', 'encartuchadeira-mediseal', 'Bascula', 'Realizar ajuste da bascula de introdução de bula e blister.', 'intermediate', 15),
  ('H196', 'encartuchadeira-mediseal', 'Armação de Cartucho', 'Realizar revisão completa do conjunto em bancada.', 'advanced', 16),
  ('H197', 'encartuchadeira-mediseal', 'Armação de Cartucho', 'Realizar a correta instalação do conjunto revisado na máquina.', 'advanced', 17),
  ('H198', 'encartuchadeira-mediseal', 'Armação de Cartucho', 'Verificar o correto alinhamento e funcionamento dos braços de retirada de cartucho e verificação do ponto zero mêcanico com eletrônico', 'advanced', 18),
  ('H199', 'encartuchadeira-mediseal', 'Armação de Cartucho', 'Verificar vazamento de vácuo entre as câmaras', 'advanced', 19),
  ('H200', 'encartuchadeira-mediseal', 'Armação de Cartucho', 'Verificar o correto funcionamento do ponto mecânico do pica-pau', 'advanced', 20),
  ('H201', 'encartuchadeira-mediseal', 'Armação de Cartucho', 'Verificar ponto zero mecânico do dobrador de abas e o correto funcionamento da fricção', 'intermediate', 21),
  ('H202', 'encartuchadeira-mediseal', 'Introdução de Blister', 'Verificar o correto funcionamento e verificação do ponto zero mêcanico com eletrônico', 'intermediate', 22),
  ('H203', 'encartuchadeira-mediseal', 'HotMelt', 'Verificar correto funcionamento dos bicos de cola quanto a vazamentos, identificação residuos de cola nas guias de fechamento, ajuste de vazão de cola e pressão pneumática dos módulos e bomba.', 'intermediate', 23),
  ('H204', 'encartuchadeira-mediseal', 'Transporte de cartucho', 'Verificar o correto funcionamento das esteiras superiores/inferiores e ponto zero mêcanico com eletrônico.', 'intermediate', 24),
  ('H205', 'encartuchadeira-mediseal', 'Transporte de cartucho (esteira superior)', 'Realizar revisão completa da esteira', 'intermediate', 25),
  ('H206', 'encartuchadeira-mediseal', 'Transporte de cartucho (esteira inferior)', 'Realizar revisão completa da esteira e regulagem dos pontos mecânicos na montagem.', 'advanced', 26),
  ('H207', 'encartuchadeira-mediseal', 'Conjunto carimbador', 'Realizar revisão completa do conjunto.', 'intermediate', 27),
  ('H208', 'encartuchadeira-mediseal', 'Conjunto carimbador', 'Realizar ajuste do ponto do carimbo com o cartucho', 'intermediate', 28),
  ('H209', 'encartuchadeira-mediseal', 'Esteira de Saída', 'Realizar revisão completa das esteiras de saídas longas e curta.', 'intermediate', 29),
  ('H210', 'encartuchadeira-mediseal', 'Sist. de Transmissão Principal', 'Verificar tensionamento e desgastes das correias', 'intermediate', 30),
  ('H211', 'encartuchadeira-mediseal', 'Sist. de Transmissão Principal', 'Realizar revisão dos redutores planetários.', 'intermediate', 31),
  ('H212', 'encartuchadeira-mediseal', 'Lubrificação', 'Limpeza e lubrificação Geral', 'basic', 32),
  ('H213', 'encartuchadeira-mediseal', 'Balança', 'Verificação das condições das esteiras de entrada, pesagem e saída, alinhamento e tensionamento e desgastes da correia sincronizada, verificação os rolamentos dos rolos', 'intermediate', 33),
  ('H214', 'encaixotadora-mediseal', 'Máquina', 'Realizar revisão completa da esteira de entrada.', 'basic', 1),
  ('H215', 'encaixotadora-mediseal', 'Magazine de Caixas', 'Verificar o correto alinhamento do magazine e se o sistema de reposição de caixas por correia sincronizada está funcionando corretamente', 'basic', 2),
  ('H216', 'encaixotadora-mediseal', 'Empilhador', 'Verificar o correto funcionamento do mecanismo de montagem e alinhamento dos cartuchos', 'intermediate', 3),
  ('H217', 'encaixotadora-mediseal', 'Armação de Caixas', 'Verificação da eficiência do vácuo, funcionamento correto da armação da caixa e ponto zero mecânico com eletrônico.', 'basic', 4),
  ('H218', 'encaixotadora-mediseal', 'Empurradores', 'Revisão do conjuto de contra-calço, guias lineares e ponto zero mecânico com eletrônico', 'intermediate', 5),
  ('H219', 'encaixotadora-mediseal', 'Esteira de saída', 'Verificar desgates das correias e ajuste do ponto zero mecnico e eletrônico do conjunto', 'basic', 6),
  ('H220', 'encaixotadora-mediseal', 'Aplicador de fita', 'Revisão completa do conjuto', 'intermediate', 7),
  ('H221', 'encaixotadora-mediseal', 'Aplicador de fita', 'Realizar ajuste de pressão das molas e posicionamento das facas', 'intermediate', 8),
  ('H222', 'encaixotadora-mediseal', 'Máquina', 'Limpeza e lubrificação Geral', 'basic', 9);

-- Marcação ou nota com chave fora do catálogo não deveria existir (a API só aceitava o catálogo); se houver, sai antes das chaves estrangeiras.
DELETE FROM "MemberMatrixEquipment" WHERE "equipment" NOT IN (SELECT "id" FROM "MatrixEquipment");
DELETE FROM "MemberSkill" WHERE "skillId" NOT IN (SELECT "id" FROM "MatrixSkill");

ALTER TABLE "MemberMatrixEquipment" RENAME COLUMN "equipment" TO "equipmentId";

CREATE INDEX "MemberMatrixEquipment_equipmentId_idx" ON "MemberMatrixEquipment"("equipmentId");
CREATE INDEX "MemberSkill_skillId_idx" ON "MemberSkill"("skillId");

ALTER TABLE "MemberMatrixEquipment" ADD CONSTRAINT "MemberMatrixEquipment_equipmentId_fkey" FOREIGN KEY ("equipmentId") REFERENCES "MatrixEquipment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MemberSkill" ADD CONSTRAINT "MemberSkill_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "MatrixSkill"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
