export const COMPETENCY_MATRIX_TITLE = "Check List de Conhecimento Específico Mecânico por Equipamento";

export const COMPETENCY_EQUIPMENTS = [
  { key: "blistadeira-cam", name: "Blistadeira CAM" },
  { key: "encartuchadeira-cam", name: "Encartuchadeira CAM" },
  { key: "encaixotadora-cam", name: "Encaixotadora CAM" },
  { key: "blistadeira-uhlmann", name: "Blistadeira Uhlmann" },
  { key: "encartuchadeira-uhlmann", name: "Encartuchadeira Uhlmann" },
  { key: "encaixotadora-uhlmann", name: "Encaixotadora Uhlmann" },
  { key: "blistadeira-mediseal", name: "Blistadeira Mediseal" },
  { key: "encartuchadeira-mediseal", name: "Encartuchadeira Mediseal" },
  { key: "encaixotadora-mediseal", name: "Encaixotadora Mediseal" },
] as const;

export type CompetencyEquipmentKey = (typeof COMPETENCY_EQUIPMENTS)[number]["key"];

export const COMPETENCY_LEVELS = ["basic", "intermediate", "advanced"] as const;
export type CompetencyLevel = (typeof COMPETENCY_LEVELS)[number];

export const COMPETENCY_LEVEL_LABELS: Record<CompetencyLevel, string> = {
  basic: "Básico",
  intermediate: "Intermediário",
  advanced: "Avançado",
};

export const COMPETENCY_LEVEL_EXPECTED: Record<CompetencyLevel, number> = {
  basic: 2,
  intermediate: 3,
  advanced: 4,
};

export type CompetencySkill = {
  id: string;
  equipment: CompetencyEquipmentKey;
  subgroup: string;
  text: string;
  level: CompetencyLevel;
};

export const COMPETENCY_SKILLS: readonly CompetencySkill[] = [
  { id: "H1", equipment: "blistadeira-cam", subgroup: "Desbobinador", text: "Identificar elementos de apoio do porta bobina e sua funcionalidade.", level: "basic" },
  { id: "H2", equipment: "blistadeira-cam", subgroup: "Desbobinador", text: "Conhecimento em fixação dos roldanas de alinhamento do material", level: "basic" },
  { id: "H3", equipment: "blistadeira-cam", subgroup: "Desbobinador", text: "Análise do circuito dos rolos de passagem quanto a travamento mecânico", level: "basic" },
  { id: "H4", equipment: "blistadeira-cam", subgroup: "Desbobinador", text: "Conhecimento em análise de folgas mecânicas no conjunto de tração", level: "basic" },
  { id: "H5", equipment: "blistadeira-cam", subgroup: "Desbobinador", text: "Análise do correto funcionamento do balancin de tensionamento do material", level: "intermediate" },
  { id: "H6", equipment: "blistadeira-cam", subgroup: "Desbobinador", text: "Ajuste em alinhamento do desbobinamento", level: "intermediate" },
  { id: "H7", equipment: "blistadeira-cam", subgroup: "Placa de Aquecimento", text: "Identificação de folgas nos eixos e guias", level: "basic" },
  { id: "H8", equipment: "blistadeira-cam", subgroup: "Placa de Aquecimento", text: "Ajuste de alinhamento entre as placas superior e inferior", level: "advanced" },
  { id: "H9", equipment: "blistadeira-cam", subgroup: "Placa de Aquecimento", text: "limpeza das placas superiores e inferiores", level: "basic" },
  { id: "H10", equipment: "blistadeira-cam", subgroup: "Estampo de Formação", text: "Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica", level: "advanced" },
  { id: "H11", equipment: "blistadeira-cam", subgroup: "Estampo de Formação", text: "Conferencia ponto zero mecânico da formação", level: "intermediate" },
  { id: "H12", equipment: "blistadeira-cam", subgroup: "Estampo de Formação", text: "Revisão do conjunto das molas prato", level: "advanced" },
  { id: "H13", equipment: "blistadeira-cam", subgroup: "Estampo de Formação", text: "Verificar o correto funcionamento do mecanismo de movimentação do pré formador", level: "advanced" },
  { id: "H14", equipment: "blistadeira-cam", subgroup: "Primeira Pinça", text: "Verificar o correto funcionamento do mecanismo da pinça, se o sistema de catraca (Rolamento contra recúo) está ok, verificar a pressão do contra rolo e condição das correias", level: "advanced" },
  { id: "H15", equipment: "blistadeira-cam", subgroup: "Segunda Pinça", text: "Identificação de folgas em eixos, rolamentos lineares, travamento da pinça, rotulas e no sistema de puxada (glifo)", level: "intermediate" },
  { id: "H16", equipment: "blistadeira-cam", subgroup: "Segunda Pinça", text: "Revisão do sistema Glifo", level: "advanced" },
  { id: "H17", equipment: "blistadeira-cam", subgroup: "Mesa de Alimentação", text: "Identificação de folgas em eixos, rolamentos lineares, rotulas e no sistema de puxada (glifo)", level: "intermediate" },
  { id: "H18", equipment: "blistadeira-cam", subgroup: "Mesa de Alimentação", text: "Ajuste de passo mecânico", level: "advanced" },
  { id: "H19", equipment: "blistadeira-cam", subgroup: "Porta Bobina de material de selagem", text: "Verificar o correto funcionamento do porta bobina e dos rolos de passagem E balancim", level: "basic" },
  { id: "H20", equipment: "blistadeira-cam", subgroup: "Estação de Selagem", text: "Revisão completa do conjunto de selagem", level: "advanced" },
  { id: "H21", equipment: "blistadeira-cam", subgroup: "Estação de Selagem", text: "Revisão do multiplicador de pressão", level: "advanced" },
  { id: "H22", equipment: "blistadeira-cam", subgroup: "Estação de Selagem", text: "Identificação de folgas mecânicas no conjunto de transmissão da selagem inferior e superior e verificação do ponto zero mecânico", level: "advanced" },
  { id: "H23", equipment: "blistadeira-cam", subgroup: "Estação de Selagem", text: "Verificar folgas nas guias de fixação das ferramentas de selagem inferior e superior", level: "intermediate" },
  { id: "H24", equipment: "blistadeira-cam", subgroup: "Estação de Selagem", text: "Verificar correto funcionamento do sistema hidropneumático e se existe indícios de vazamento de óleo", level: "advanced" },
  { id: "H25", equipment: "blistadeira-cam", subgroup: "Estação de Refrigeração selagem", text: "Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica", level: "intermediate" },
  { id: "H26", equipment: "blistadeira-cam", subgroup: "Terceira Pinça", text: "Identificação de folgas em eixos, rolamentos lineares, travamento da pinça, rotulas e no sistema de puxada (glifo)", level: "intermediate" },
  { id: "H27", equipment: "blistadeira-cam", subgroup: "Quarta Pinça", text: "Conhecimento em sistema mecânico para identificação de folgas em eixos, rolamentos lineares e desgaste na placa superior de apoio da manta", level: "intermediate" },
  { id: "H28", equipment: "blistadeira-cam", subgroup: "Estação de Corte", text: "Revisão do sistema de corte e identificação do ponto zero mecânico", level: "advanced" },
  { id: "H29", equipment: "blistadeira-cam", subgroup: "Transferência de Blister", text: "Verificar folgas no conjunto mecânico do porta ventosa, funcionamento do vácuo e identificação do ponto mecânico", level: "advanced" },
  { id: "H30", equipment: "blistadeira-cam", subgroup: "Transferência de Blister", text: "Revisão completa do conjunto da esteira de saída.", level: "intermediate" },
  { id: "H31", equipment: "blistadeira-cam", subgroup: "Transferência de Blister", text: "Revisão completa do conjunto do acelerador de blister.", level: "intermediate" },
  { id: "H32", equipment: "blistadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Revisão completa do redutor de transmissão principal", level: "advanced" },
  { id: "H33", equipment: "blistadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Verificação do conjunto de transmissão quanto a folgas no redutor, entre redutor e eixo principal, desgastes de correntes e coroas.", level: "intermediate" },
  { id: "H34", equipment: "blistadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Realizar o alinhamento de transmissão por corrente, polia/correia e desgastes mecânicos", level: "intermediate" },
  { id: "H35", equipment: "blistadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Conhecimento em ajuste do freio motor conforme manual do fabricante", level: "intermediate" },
  { id: "H36", equipment: "blistadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Verificação do ponto zero mecânico com eletrônico da máquina", level: "advanced" },
  { id: "H37", equipment: "blistadeira-cam", subgroup: "Lubrificação", text: "Lubrificação Geral", level: "basic" },
  { id: "H38", equipment: "encartuchadeira-cam", subgroup: "Magazine de Blister", text: "Ajuste e calibração das garrinhas de seleção de blister, e revisão completa dos sub conjuntos.", level: "advanced" },
  { id: "H39", equipment: "encartuchadeira-cam", subgroup: "Esteira Transporte de Blister", text: "Identificação de folgas no sistema de transmissão por corrente, identificação de tensionamento e desgastes da corrente, verificar se existem folgas mecânicas no conjunto carrinhos e eixos", level: "advanced" },
  { id: "H40", equipment: "encartuchadeira-cam", subgroup: "Esteira Transporte de Blister", text: "Lubrificação e limpeza dos conjunto", level: "basic" },
  { id: "H41", equipment: "encartuchadeira-cam", subgroup: "GUK", text: "Revisão geral do guk", level: "advanced" },
  { id: "H42", equipment: "encartuchadeira-cam", subgroup: "GUK", text: "Verificar se há folgas no sistema de transmissão por eixos e engrenagens e servo acionamento. Identificar o ponto zero mecânico do GUK.", level: "advanced" },
  { id: "H43", equipment: "encartuchadeira-cam", subgroup: "GUK", text: "Realizar limpeza e lubrificação", level: "basic" },
  { id: "H44", equipment: "encartuchadeira-cam", subgroup: "GUK", text: "Verificação de folgas ou excesso de pressão entre rolos de dobra de bula e identificação de desgaste da borracha e recartilho do rolo.", level: "advanced" },
  { id: "H45", equipment: "encartuchadeira-cam", subgroup: "GUK", text: "Verificar sistema de vácuo se existem possíveis ponto de perda de vácuo e identificação do ponto mecânico de acionamento do vácuo.", level: "advanced" },
  { id: "H46", equipment: "encartuchadeira-cam", subgroup: "Magazine de Cartucho", text: "Verificar o correto funcionamento do sistema de transporte de cartucho por esteira sincronizada e se existem folgas no sistema de acionamento", level: "intermediate" },
  { id: "H47", equipment: "encartuchadeira-cam", subgroup: "Armação de Cartucho", text: "Revisão completa do eixo vertical", level: "advanced" },
  { id: "H48", equipment: "encartuchadeira-cam", subgroup: "Armação de Cartucho", text: "Revisar conjunto do cicloide de armação de cartucho", level: "advanced" },
  { id: "H49", equipment: "encartuchadeira-cam", subgroup: "Armação de Cartucho", text: "Verificar a eficiência do sistema de vácuo e se as válvulas de abertura e fechamento de vácuo estão funcionando corretamente", level: "advanced" },
  { id: "H50", equipment: "encartuchadeira-cam", subgroup: "Armação de Cartucho", text: "Revisar sistema de transmissão por eixos e engrenagens e correia sincronizada", level: "advanced" },
  { id: "H51", equipment: "encartuchadeira-cam", subgroup: "Armação de Cartucho", text: "Verificar o correto alinhamento e funcionamento dos braços de retirada de cartucho", level: "intermediate" },
  { id: "H52", equipment: "encartuchadeira-cam", subgroup: "Introdução de Blister", text: "Revisão completa do conjunto de empurradores", level: "advanced" },
  { id: "H53", equipment: "encartuchadeira-cam", subgroup: "Introdução de Blister", text: "Verificar se existem folgas mecânicas nas correntes de transmissão, eixos, buchas e carrinhos dos empurradores e verificar o correto sincronismo com as canecas", level: "advanced" },
  { id: "H54", equipment: "encartuchadeira-cam", subgroup: "Introdução de Blister", text: "Verificar possíveis folgas e desalinhamento das guias de avanço e retorno dos empurradores", level: "advanced" },
  { id: "H55", equipment: "encartuchadeira-cam", subgroup: "Introdução de Blister", text: "Realizar a correta limpeza e lubrificação dos eixos, guias e correntes", level: "basic" },
  { id: "H56", equipment: "encartuchadeira-cam", subgroup: "Hotmelt", text: "Verificar correto funcionamento dos bicos de cola quanto a vazamentos, identificação residuos de cola nas guias de fechamento e ajuste de vazão de cola e pressão pneumática dos módulos e bomba", level: "intermediate" },
  { id: "H57", equipment: "encartuchadeira-cam", subgroup: "Sistema de fechamento de cartucho", text: "Verificar guias de montagem do cartucho, pinça do fechamento de abas e guias de fechamento de abas.", level: "intermediate" },
  { id: "H58", equipment: "encartuchadeira-cam", subgroup: "Sistema de transporte de cartuchos", text: "Revisão completa do conjunto de transmissão", level: "advanced" },
  { id: "H59", equipment: "encartuchadeira-cam", subgroup: "Esteira de Saída", text: "Revisão do rolo do conjunto de transmissão da esteira de saída", level: "intermediate" },
  { id: "H60", equipment: "encartuchadeira-cam", subgroup: "Esteira de Saída", text: "Verificação de alinhamento das correias e possíveis folgas no conjunto de transmissão mecânica dos rolos", level: "intermediate" },
  { id: "H61", equipment: "encartuchadeira-cam", subgroup: "Esteira de Saída", text: "Lubrificação e limpeza dos conjunto", level: "basic" },
  { id: "H62", equipment: "encartuchadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Alinhamento de transmissão por corrente, polia/correia e desgastes mecânicos", level: "advanced" },
  { id: "H63", equipment: "encartuchadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Conhecimento em ajuste do freio motor conforme manual do fabricante", level: "advanced" },
  { id: "H64", equipment: "encartuchadeira-cam", subgroup: "Sist. de Transmissão Principal", text: "Verificação do ponto zero mecânico com eletrônico da máquina com verificação dos segintes conjuntos: ciclóide, transporte de canecas, engrenagens do sistema de fechamento nos lados dianteiros e traseiro", level: "advanced" },
  { id: "H65", equipment: "encartuchadeira-cam", subgroup: "Transporte de canecas", text: "Revisão completa do conjunto de carrinho e caneca", level: "advanced" },
  { id: "H66", equipment: "encartuchadeira-cam", subgroup: "Transporte de canecas", text: "Regulagem do tencionamento da corrente com o sensor (Alarme S 27)", level: "intermediate" },
  { id: "H67", equipment: "encartuchadeira-cam", subgroup: "Lubrificação", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H68", equipment: "encartuchadeira-cam", subgroup: "Balança", text: "Verificação das condições das esteiras de entrada, pesagem e saída, alinhamento e tensionamento e desgastes da correia sincronizada, verificação os rolamentos dos rolos", level: "intermediate" },
  { id: "H69", equipment: "encaixotadora-cam", subgroup: "Esteira de entrada", text: "Revisão completa do conjunto da esteira de entrada.", level: "intermediate" },
  { id: "H70", equipment: "encaixotadora-cam", subgroup: "Empilhador", text: "Verificar se está realizando o correto empilhamento, se o sistema de elevação e contra elevação estão funcionando corretamente", level: "intermediate" },
  { id: "H71", equipment: "encaixotadora-cam", subgroup: "Armação de Caixas", text: "Verificar correto funcionamento do sistema de vácuo e sua eficiência.", level: "intermediate" },
  { id: "H72", equipment: "encaixotadora-cam", subgroup: "Armação de Caixas", text: "Verificar o correto funcionamento do mecanismo de montagem e alinhamento de caixa", level: "intermediate" },
  { id: "H73", equipment: "encaixotadora-cam", subgroup: "Armação de Caixas", text: "Revisão do sistema de transmissão de armação (redutor, came e eixo)", level: "advanced" },
  { id: "H74", equipment: "encaixotadora-cam", subgroup: "Empurradores", text: "Verificação da eficiência da transferencia dos cartuchos e o correto ajuste de entrodução dos cartuchos na caixa de embarque.", level: "intermediate" },
  { id: "H75", equipment: "encaixotadora-cam", subgroup: "Fechamento de Caixas", text: "Verificar o correto funcionamento das esterias de transporte da caixa de embarque, desgaste e folga mecânica nos rolos de transporte. Verificar o correto ajuste nas guias de dobramento das abas. Verificar a correta aplicação da fita de fechamento.", level: "intermediate" },
  { id: "H76", equipment: "encaixotadora-cam", subgroup: "Sist. de Transmissão Principal", text: "Verificação do ponto zero mecânico com eletrônico da máquina.", level: "advanced" },
  { id: "H77", equipment: "encaixotadora-cam", subgroup: "Lubrificação", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H78", equipment: "blistadeira-uhlmann", subgroup: "Desbobinador", text: "Verificar elementos de apoio do porta bobinas (Freios porta bobina, eixos infláveis, proteções) se estão funcionando corretamente.", level: "basic" },
  { id: "H79", equipment: "blistadeira-uhlmann", subgroup: "Desbobinador", text: "Realizar calibração do sistema automático de centralização da manta.", level: "advanced" },
  { id: "H80", equipment: "blistadeira-uhlmann", subgroup: "Desbobinador", text: "Realizar centralização manual da manta no desbobinador.", level: "intermediate" },
  { id: "H81", equipment: "blistadeira-uhlmann", subgroup: "Desbobinador", text: "Revisão geral dos rolos de passagem do desbobinador.", level: "basic" },
  { id: "H82", equipment: "blistadeira-uhlmann", subgroup: "Desbobinador", text: "Realizar ajuste correto do pulmão.", level: "basic" },
  { id: "H83", equipment: "blistadeira-uhlmann", subgroup: "Placa de Aquecimento", text: "Identificação de folgas mecânicas e eletrônicos no conjunto de movimentação das placas de aquecimento Inferior e superior (Terminais de rotula e guias lineares).", level: "intermediate" },
  { id: "H84", equipment: "blistadeira-uhlmann", subgroup: "Placa de Aquecimento", text: "Ajuste de alinhamento entre as placas superior e inferior e limpeza.", level: "advanced" },
  { id: "H85", equipment: "blistadeira-uhlmann", subgroup: "Placa de Aquecimento", text: "Verificar funcionamento do stop das placas de aquecimento.", level: "intermediate" },
  { id: "H86", equipment: "blistadeira-uhlmann", subgroup: "Estampo de Formação", text: "Troca e calibração do conjunto de mola pratos.", level: "advanced" },
  { id: "H87", equipment: "blistadeira-uhlmann", subgroup: "Estampo de Formação", text: "Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica e vazamentos.", level: "basic" },
  { id: "H88", equipment: "blistadeira-uhlmann", subgroup: "Estampo de Formação", text: "Conferência ponto zero mecânico da formação via interface IHM.", level: "advanced" },
  { id: "H89", equipment: "blistadeira-uhlmann", subgroup: "Estampo de Formação", text: "Verificar folgas ou desgastes no sistema de trava da ferramenta superior e inferior.", level: "basic" },
  { id: "H90", equipment: "blistadeira-uhlmann", subgroup: "Estampo de Formação", text: "Verificar funcionamento e se existe vazamento das vávulas de entrada e saída de ar de formação.", level: "intermediate" },
  { id: "H91", equipment: "blistadeira-uhlmann", subgroup: "Pinça de Puxada pós Formação", text: "Verificar o correto funcionamento do acionamento da pinça. Verificar o desgaste e a calibração dos batoques de travamento da pinça e verificar a movimentação mecânica de puxada da manta.", level: "intermediate" },
  { id: "H92", equipment: "blistadeira-uhlmann", subgroup: "Balacin de Controle da Manta", text: "Verificar o correto zeramento do encoder.", level: "advanced" },
  { id: "H93", equipment: "blistadeira-uhlmann", subgroup: "Mesa de Alimentação", text: "Revisão geral do conjunto da escova transversal e mescladores.", level: "intermediate" },
  { id: "H94", equipment: "blistadeira-uhlmann", subgroup: "Mesa de Alimentação", text: "Revisão geral do conjunto alimentador Simtap", level: "intermediate" },
  { id: "H95", equipment: "blistadeira-uhlmann", subgroup: "Mesa de Alimentação", text: "Verificar correto funcionamento da calha de alimentação.", level: "intermediate" },
  { id: "H96", equipment: "blistadeira-uhlmann", subgroup: "Porta Bobina de material de selagem", text: "Verificar o correto funcionamento do porta bobina e dos rolos de passagem , incluindo os rolos do TIJ.", level: "intermediate" },
  { id: "H97", equipment: "blistadeira-uhlmann", subgroup: "Estação de Selagem", text: "Revisão geral do conjunto do rolo de selagem (com apoio do eletricista).", level: "intermediate" },
  { id: "H98", equipment: "blistadeira-uhlmann", subgroup: "Estação de Selagem", text: "Verificar folgas ou desgastes no sistema da trava do rolo da ferramenta de selagem.", level: "basic" },
  { id: "H99", equipment: "blistadeira-uhlmann", subgroup: "Estação de Selagem", text: "Verificar correto funcionamento do sistema pneumático de acionamento do rolo quente de selagem.", level: "basic" },
  { id: "H100", equipment: "blistadeira-uhlmann", subgroup: "Estação de Refrigeração no Rolo de Selagem", text: "Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica e vazamentos.", level: "intermediate" },
  { id: "H101", equipment: "blistadeira-uhlmann", subgroup: "Rolo de Puxada do Filme", text: "Verificar possiveis desgastes no rolo, possiveis desalinhamentos entre os extremos do rolo, folga nos rolamentos e o correto travamento da manta após o fechamento do rolo movél.", level: "intermediate" },
  { id: "H102", equipment: "blistadeira-uhlmann", subgroup: "Estação de Corte", text: "Verificar possíveis folgas no conjunto de movimento do corte, verificar se a contra-faca está cortando com eficiência o retalho do blister.", level: "advanced" },
  { id: "H103", equipment: "blistadeira-uhlmann", subgroup: "Transferência de Blister", text: "Verificar o alinhamento do porta ventosa, verificar o sincronismo de entrega de blisters com a esteira de transferência, verificar a eficiência do vácuo da PIAB.", level: "advanced" },
  { id: "H104", equipment: "blistadeira-uhlmann", subgroup: "Transferência de Blister", text: "Verificar o tensionamento e alinhamento das esteiras de transporte de blisters, verificar se há desgaste internamente nas esteiras, verificar se há existem desagastes nas abas das polias próximo ao porta ventosa, verificar a eficiência de vácuo nas esteiras e realizar a troca das esteiras.", level: "intermediate" },
  { id: "H105", equipment: "blistadeira-uhlmann", subgroup: "Transferência de Blister", text: "Verificar o correto funcionamento dos batedores e dos stops de blisters. Realizar revisão e limpeza.", level: "intermediate" },
  { id: "H106", equipment: "blistadeira-uhlmann", subgroup: "Sist. de Transmissão Geral", text: "Revisão dos redutores planetários.", level: "basic" },
  { id: "H107", equipment: "blistadeira-uhlmann", subgroup: "Lubrificação", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H108", equipment: "encartuchadeira-uhlmann", subgroup: "Magazine de Blister", text: "Ajuste e calibração dos discos de seleção de blister, servo de acionamento e folgas no conjunto mecânico. Verificação do ponto de entrega de blister na esteira.", level: "basic" },
  { id: "H109", equipment: "encartuchadeira-uhlmann", subgroup: "Esteira Transporte de Blister", text: "Verificar o correto funcionamento da esteira", level: "intermediate" },
  { id: "H110", equipment: "encartuchadeira-uhlmann", subgroup: "GUK", text: "Verificar se há folgas no sistema de transmissão por eixos e engrenagens e servo acionamento. Identificar o ponto zero mecânico do GUK.", level: "advanced" },
  { id: "H111", equipment: "encartuchadeira-uhlmann", subgroup: "GUK", text: "Realizar limpeza e lubrificação", level: "basic" },
  { id: "H112", equipment: "encartuchadeira-uhlmann", subgroup: "GUK", text: "Verificação de folgas ou excesso de pressão entre rolos de dobra de bula e identificação de desgaste da borracha e recartilho do rolo.", level: "intermediate" },
  { id: "H113", equipment: "encartuchadeira-uhlmann", subgroup: "GUK", text: "Verificar sistema de vácuo se existem possíveis ponto de perda de vácuo e identificação do ponto mecânico de acionamento do vácuo.", level: "advanced" },
  { id: "H114", equipment: "encartuchadeira-uhlmann", subgroup: "Magazine de Cartucho", text: "Verificar o correto funcionamento do sistema de transporte de cartucho por esteira sincronizada e se existem folgas no sistema de acionamento", level: "intermediate" },
  { id: "H115", equipment: "encartuchadeira-uhlmann", subgroup: "Armação de Cartucho", text: "Verificar possíveis folgas no sistema de transmissão por eixos e engrenagens e correia sincronizada", level: "advanced" },
  { id: "H116", equipment: "encartuchadeira-uhlmann", subgroup: "Armação de Cartucho", text: "Verificar o correto alinhamento e funcionamento dos braços de retirada de cartucho", level: "intermediate" },
  { id: "H117", equipment: "encartuchadeira-uhlmann", subgroup: "Introdução de Blister", text: "Verificar se existem folgas mecânicas nas correntes de transmissão, eixos, buchas e carrinhos dos empurradores e verificar o correto sincronismo com os pentes", level: "advanced" },
  { id: "H118", equipment: "encartuchadeira-uhlmann", subgroup: "Introdução de Blister", text: "Verificar possíveis folgas e desalinhamento das guias de avanço e retorno dos empurradores", level: "intermediate" },
  { id: "H119", equipment: "encartuchadeira-uhlmann", subgroup: "Introdução de Blister", text: "Realizar a correta limpeza e lubrificação dos eixos, guias e correntes", level: "basic" },
  { id: "H120", equipment: "encartuchadeira-uhlmann", subgroup: "Empurradores", text: "Verificar o correto funcionamento do conjunto de empurradores", level: "advanced" },
  { id: "H121", equipment: "encartuchadeira-uhlmann", subgroup: "HotMelt", text: "Verificar correto funcionamento dos bicos de cola quanto a vazamentos, identificação residuos de cola nas guias de fechamento e ajuste de vazão de cola e pressão pneumática dos módulos e bomba.", level: "intermediate" },
  { id: "H122", equipment: "encartuchadeira-uhlmann", subgroup: "Fechamento de cartucho", text: "Verificar o correto funcionamento do datador domino", level: "basic" },
  { id: "H123", equipment: "encartuchadeira-uhlmann", subgroup: "Sistema de fechamento de cartucho", text: "Verificar guias de montagem do cartucho, pinça do fechamento de abas e guias de fechamento de abas.", level: "intermediate" },
  { id: "H124", equipment: "encartuchadeira-uhlmann", subgroup: "Esteira de Saída", text: "Verificação de alinhamento das correias e possíveis folgas no conjunto de transmissão mecânica dos rolos", level: "intermediate" },
  { id: "H125", equipment: "encartuchadeira-uhlmann", subgroup: "Esteira de Saída", text: "Lubrificação e limpeza dos conjunto", level: "basic" },
  { id: "H126", equipment: "encartuchadeira-uhlmann", subgroup: "Sist. de Transmissão Principal", text: "Alinhamento de transmissão por corrente, polia/correia e desgastes mecânicos", level: "advanced" },
  { id: "H127", equipment: "encartuchadeira-uhlmann", subgroup: "Lubrificação", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H128", equipment: "encartuchadeira-uhlmann", subgroup: "Sist. de Transmissão Principal", text: "Verificação do ponto zero mecânico com eletrônico da máquina, verificando o zero eletrôncio do encoder com o zero mecânico da maquina.", level: "intermediate" },
  { id: "H129", equipment: "encartuchadeira-uhlmann", subgroup: "Balança", text: "Verificação das condições das esteiras de entrada, pesagem e saída, alinhamento e tensionamento e desgastes da correia sincronizada, verificação os rolamentos dos rolos", level: "intermediate" },
  { id: "H130", equipment: "encaixotadora-uhlmann", subgroup: "Magazine de Caixas", text: "Verificação o correto alinhamento do magazine e se o sistema de reposição de caixas por correia sincronizada está funcionando corretamente", level: "advanced" },
  { id: "H131", equipment: "encaixotadora-uhlmann", subgroup: "Magazine de Caixas", text: "Verificar se está realizando o correto empilhamento, se o sistema de elevação e contra elevação estão funcionando corretamente", level: "intermediate" },
  { id: "H132", equipment: "encaixotadora-uhlmann", subgroup: "Magazine de Caixas", text: "Verificar correto funcionamento do sistema de vácuo e sua eficiência.", level: "intermediate" },
  { id: "H133", equipment: "encaixotadora-uhlmann", subgroup: "Esteira de entrada", text: "Verificar correto funcionamento de tração da esteira se existem folgas mecanicas no conjunto.", level: "basic" },
  { id: "H134", equipment: "encaixotadora-uhlmann", subgroup: "Empilhador", text: "Verificar o correto funcionamento do mecanismo de montagem e alinhamento de caixa", level: "intermediate" },
  { id: "H135", equipment: "encaixotadora-uhlmann", subgroup: "Armação de Caixas", text: "Verificação da eficiência da transferencia dos cartuchos e o correto ajuste de introdução dos cartuchos na caixa de embarque.", level: "intermediate" },
  { id: "H136", equipment: "encaixotadora-uhlmann", subgroup: "Empurradores", text: "Verificar o correto funcionamento das esterias de transporte da caixa de embarque, desgaste e folga mecânica nos rolos de transporte. Verificar o correto ajuste nas guias de dobramento das abas. Verificar a correta aplicação da fita de fechamento.", level: "intermediate" },
  { id: "H137", equipment: "encaixotadora-uhlmann", subgroup: "Empurradores", text: "Verificação do ponto zero mecânico com eletrônico da máquina.", level: "intermediate" },
  { id: "H138", equipment: "encaixotadora-uhlmann", subgroup: "Sist. de Transmissão Principal", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H139", equipment: "encaixotadora-uhlmann", subgroup: "Sist. de Transmissão Principal", text: "Ajuste de parâmetro do formato", level: "basic" },
  { id: "H140", equipment: "encaixotadora-uhlmann", subgroup: "Sist. de Transmissão Principal", text: "Verificar o correto funcionamento do sistema de vácuo", level: "basic" },
  { id: "H141", equipment: "blistadeira-mediseal", subgroup: "Bistadeira", text: "Realizar os zeramentos de todos os pontos de formato da máquina.", level: "advanced" },
  { id: "H142", equipment: "blistadeira-mediseal", subgroup: "Desbobinador", text: "Identificar elementos (carrinho) de apoio do porta bobina e sua funcionalidade.", level: "basic" },
  { id: "H143", equipment: "blistadeira-mediseal", subgroup: "Desbobinador", text: "Revisão conjunto do redutor e acoplamento de tração da bobina", level: "intermediate" },
  { id: "H144", equipment: "blistadeira-mediseal", subgroup: "Desbobinador", text: "Análise do circuito dos rolos de passagem quanto a travamento mecânico", level: "basic" },
  { id: "H145", equipment: "blistadeira-mediseal", subgroup: "Desbobinador", text: "Conhecimento em análise de desgastes mecânicos no rolo de tração da manta.", level: "basic" },
  { id: "H146", equipment: "blistadeira-mediseal", subgroup: "Placa de Aquecimento", text: "Identificação de folgas mecânicas no conjunto de movimentação das placas de aquecimento.", level: "intermediate" },
  { id: "H147", equipment: "blistadeira-mediseal", subgroup: "Placa de Aquecimento", text: "Ajuste e alinhamento das placas do forno.", level: "advanced" },
  { id: "H148", equipment: "blistadeira-mediseal", subgroup: "Disco de puxada de filme da Formação", text: "Verificar possíveis desgaste nos discos e calibração.", level: "intermediate" },
  { id: "H149", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Revisão completa do conjunto da base da placa de formação.", level: "advanced" },
  { id: "H150", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Verificação do ponto zero da formação principal e da formação mecânica.", level: "intermediate" },
  { id: "H151", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Zeramento do reloginho de ajuste do pré punção.", level: "intermediate" },
  { id: "H152", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Limpeza completa do sistema de arrefecimento.", level: "intermediate" },
  { id: "H153", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Conferencia ponto zero mecânico da formação via interface IHM.", level: "intermediate" },
  { id: "H154", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Verificar folgas ou desgastes no sistema de travas das ferramentas, verificar se existem vazamentos de água.", level: "intermediate" },
  { id: "H155", equipment: "blistadeira-mediseal", subgroup: "Estampo de Formação", text: "Revisão do conjunto de molas prato.", level: "advanced" },
  { id: "H156", equipment: "blistadeira-mediseal", subgroup: "Balacin pós formação", text: "Verificar o correto zeramento do encoder.", level: "intermediate" },
  { id: "H157", equipment: "blistadeira-mediseal", subgroup: "Alimentação", text: "Ajuste de vibração do vibrador da calha de alimentação.", level: "intermediate" },
  { id: "H158", equipment: "blistadeira-mediseal", subgroup: "Porta Bobina de material de selagem", text: "Identificar elementos (carrinho) de apoio do porta bobina e sua funcionalidade.", level: "basic" },
  { id: "H159", equipment: "blistadeira-mediseal", subgroup: "Porta Bobina de material de selagem", text: "Análise do correto funcionamento do balancin de tração do material", level: "basic" },
  { id: "H160", equipment: "blistadeira-mediseal", subgroup: "Porta Bobina de material de selagem", text: "Analise de funcionamento do controle de canto do alumínio.", level: "intermediate" },
  { id: "H161", equipment: "blistadeira-mediseal", subgroup: "Estação de Selagem", text: "Revisão no conjunto do rolo quente de selagem.", level: "advanced" },
  { id: "H162", equipment: "blistadeira-mediseal", subgroup: "Estação de Selagem", text: "Verificar folgas ou desgastes no sistema de trava do rolo de selagem.", level: "intermediate" },
  { id: "H163", equipment: "blistadeira-mediseal", subgroup: "Estação de Selagem", text: "Verificar correto funcionamento do sistema pneumático de acionamento do rolo de selagem quente e se existem indícios de desgastes mecânicos.", level: "advanced" },
  { id: "H164", equipment: "blistadeira-mediseal", subgroup: "Estação de Selagem", text: "Verificação do ponto zero mecânico com eletrônico.", level: "advanced" },
  { id: "H165", equipment: "blistadeira-mediseal", subgroup: "Estação de Selagem", text: "Verificação do correto funciomento do trocador de calor da selagem.", level: "advanced" },
  { id: "H166", equipment: "blistadeira-mediseal", subgroup: "Estação de Refrigeração no Rolo de Selagem", text: "Verificar o sistema de refrigeração e climatização quanto a sua eficiência de troca térmica e junta rotativa.", level: "intermediate" },
  { id: "H167", equipment: "blistadeira-mediseal", subgroup: "Balacin de Controle da Manta pós Selagem", text: "Verificar o correto zeramento do encoder.", level: "advanced" },
  { id: "H168", equipment: "blistadeira-mediseal", subgroup: "Disco de Puxada de filme da perfuração", text: "Verificar possíveis desgaste nos discos e calibração.", level: "intermediate" },
  { id: "H169", equipment: "blistadeira-mediseal", subgroup: "disco de puxada do filme de corte", text: "Verificar possíveis desgaste nos disco e calibração.", level: "intermediate" },
  { id: "H170", equipment: "blistadeira-mediseal", subgroup: "Estação de carimbo de blister", text: "Revisão do conjunto do carimbo", level: "advanced" },
  { id: "H171", equipment: "blistadeira-mediseal", subgroup: "Estação de Corte", text: "Revisão do conjunto do sistema de corte.", level: "advanced" },
  { id: "H172", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Revisão do cicloide de blister.", level: "advanced" },
  { id: "H173", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Montagem do cicloide de blister no equipamento.", level: "advanced" },
  { id: "H174", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Teste de vazamento entre as câmaras do cicloide.", level: "advanced" },
  { id: "H175", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Verificar ponto zero do sistema de cicloide, faca e carimbo", level: "advanced" },
  { id: "H176", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Revisão da bomba de vácuo.", level: "basic" },
  { id: "H177", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Verificar a eficiência do vácuo da bomba.", level: "basic" },
  { id: "H178", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Verificar o tensionamento e alinhamento das esteiras de transporte de blisters, e ponto zero das esteiras de blisters.", level: "intermediate" },
  { id: "H179", equipment: "blistadeira-mediseal", subgroup: "Transferência de Blister", text: "Revisão completa do trânsferidor de blister e zeramento.", level: "intermediate" },
  { id: "H180", equipment: "blistadeira-mediseal", subgroup: "Lubrificação", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H181", equipment: "encartuchadeira-mediseal", subgroup: "Compensador de blister", text: "Verificar ponto zero mecânico com eletrônico, e revisão mecânica", level: "intermediate" },
  { id: "H182", equipment: "encartuchadeira-mediseal", subgroup: "Magazine de Blister", text: "Verificar ponto zero mecânico com eletrônico, e revisão mecânica", level: "intermediate" },
  { id: "H183", equipment: "encartuchadeira-mediseal", subgroup: "Esteira Curta e Longa deTransporte de Blister", text: "Revisão completa do conjunto (Transporte e Elevação) e verificação do ponto zero mêcanico com eletônico", level: "intermediate" },
  { id: "H184", equipment: "encartuchadeira-mediseal", subgroup: "GUK", text: "Revisão geral do guk", level: "advanced" },
  { id: "H185", equipment: "encartuchadeira-mediseal", subgroup: "GUK", text: "Verificar se há folgas no sistema de transmissão por eixos e engrenagens e servo acionamento. Identificar o ponto zero mecânico do GUK.", level: "advanced" },
  { id: "H186", equipment: "encartuchadeira-mediseal", subgroup: "GUK", text: "Realizar limpeza e lubrificação", level: "basic" },
  { id: "H187", equipment: "encartuchadeira-mediseal", subgroup: "GUK", text: "Verificação de folgas ou excesso de pressão entre rolos de dobra de bula e identificação de desgaste da borracha e recartilho do rolo.", level: "advanced" },
  { id: "H188", equipment: "encartuchadeira-mediseal", subgroup: "GUK", text: "Verificar sistema de vácuo se existem possíveis ponto de perda de vácuo e identificação do ponto mecânico de acionamento do vácuo.", level: "advanced" },
  { id: "H189", equipment: "encartuchadeira-mediseal", subgroup: "Transporte de bula (Correia)", text: "Realizar troca e ajustes das correias de transporte e revisão do conjunto.", level: "advanced" },
  { id: "H190", equipment: "encartuchadeira-mediseal", subgroup: "Transporte de bula", text: "Análise do correto funcionamento dos rolos separadores e stop de bula.", level: "advanced" },
  { id: "H191", equipment: "encartuchadeira-mediseal", subgroup: "Transporte de bula (Pinças)", text: "Realizar revisão das pinças, guias de abertura, troca da correia e verificação do ponto zero mêcanico com eletônico.", level: "intermediate" },
  { id: "H192", equipment: "encartuchadeira-mediseal", subgroup: "Empilhamento de blister", text: "Realizar revisão completa do conjunto em bancada.", level: "advanced" },
  { id: "H193", equipment: "encartuchadeira-mediseal", subgroup: "Empilhamento de blister", text: "Realizar ajuste do empilhador de blisters conforme procedimento, e verificação do ponto zero mêcanico com eletônico", level: "advanced" },
  { id: "H194", equipment: "encartuchadeira-mediseal", subgroup: "Bascula", text: "Realizar revisão completa do conjunto em bancada.", level: "intermediate" },
  { id: "H195", equipment: "encartuchadeira-mediseal", subgroup: "Bascula", text: "Realizar ajuste da bascula de introdução de bula e blister.", level: "intermediate" },
  { id: "H196", equipment: "encartuchadeira-mediseal", subgroup: "Armação de Cartucho", text: "Realizar revisão completa do conjunto em bancada.", level: "advanced" },
  { id: "H197", equipment: "encartuchadeira-mediseal", subgroup: "Armação de Cartucho", text: "Realizar a correta instalação do conjunto revisado na máquina.", level: "advanced" },
  { id: "H198", equipment: "encartuchadeira-mediseal", subgroup: "Armação de Cartucho", text: "Verificar o correto alinhamento e funcionamento dos braços de retirada de cartucho e verificação do ponto zero mêcanico com eletrônico", level: "advanced" },
  { id: "H199", equipment: "encartuchadeira-mediseal", subgroup: "Armação de Cartucho", text: "Verificar vazamento de vácuo entre as câmaras", level: "advanced" },
  { id: "H200", equipment: "encartuchadeira-mediseal", subgroup: "Armação de Cartucho", text: "Verificar o correto funcionamento do ponto mecânico do pica-pau", level: "advanced" },
  { id: "H201", equipment: "encartuchadeira-mediseal", subgroup: "Armação de Cartucho", text: "Verificar ponto zero mecânico do dobrador de abas e o correto funcionamento da fricção", level: "intermediate" },
  { id: "H202", equipment: "encartuchadeira-mediseal", subgroup: "Introdução de Blister", text: "Verificar o correto funcionamento e verificação do ponto zero mêcanico com eletrônico", level: "intermediate" },
  { id: "H203", equipment: "encartuchadeira-mediseal", subgroup: "HotMelt", text: "Verificar correto funcionamento dos bicos de cola quanto a vazamentos, identificação residuos de cola nas guias de fechamento, ajuste de vazão de cola e pressão pneumática dos módulos e bomba.", level: "intermediate" },
  { id: "H204", equipment: "encartuchadeira-mediseal", subgroup: "Transporte de cartucho", text: "Verificar o correto funcionamento das esteiras superiores/inferiores e ponto zero mêcanico com eletrônico.", level: "intermediate" },
  { id: "H205", equipment: "encartuchadeira-mediseal", subgroup: "Transporte de cartucho (esteira superior)", text: "Realizar revisão completa da esteira", level: "intermediate" },
  { id: "H206", equipment: "encartuchadeira-mediseal", subgroup: "Transporte de cartucho (esteira inferior)", text: "Realizar revisão completa da esteira e regulagem dos pontos mecânicos na montagem.", level: "advanced" },
  { id: "H207", equipment: "encartuchadeira-mediseal", subgroup: "Conjunto carimbador", text: "Realizar revisão completa do conjunto.", level: "intermediate" },
  { id: "H208", equipment: "encartuchadeira-mediseal", subgroup: "Conjunto carimbador", text: "Realizar ajuste do ponto do carimbo com o cartucho", level: "intermediate" },
  { id: "H209", equipment: "encartuchadeira-mediseal", subgroup: "Esteira de Saída", text: "Realizar revisão completa das esteiras de saídas longas e curta.", level: "intermediate" },
  { id: "H210", equipment: "encartuchadeira-mediseal", subgroup: "Sist. de Transmissão Principal", text: "Verificar tensionamento e desgastes das correias", level: "intermediate" },
  { id: "H211", equipment: "encartuchadeira-mediseal", subgroup: "Sist. de Transmissão Principal", text: "Realizar revisão dos redutores planetários.", level: "intermediate" },
  { id: "H212", equipment: "encartuchadeira-mediseal", subgroup: "Lubrificação", text: "Limpeza e lubrificação Geral", level: "basic" },
  { id: "H213", equipment: "encartuchadeira-mediseal", subgroup: "Balança", text: "Verificação das condições das esteiras de entrada, pesagem e saída, alinhamento e tensionamento e desgastes da correia sincronizada, verificação os rolamentos dos rolos", level: "intermediate" },
  { id: "H214", equipment: "encaixotadora-mediseal", subgroup: "Máquina", text: "Realizar revisão completa da esteira de entrada.", level: "basic" },
  { id: "H215", equipment: "encaixotadora-mediseal", subgroup: "Magazine de Caixas", text: "Verificar o correto alinhamento do magazine e se o sistema de reposição de caixas por correia sincronizada está funcionando corretamente", level: "basic" },
  { id: "H216", equipment: "encaixotadora-mediseal", subgroup: "Empilhador", text: "Verificar o correto funcionamento do mecanismo de montagem e alinhamento dos cartuchos", level: "intermediate" },
  { id: "H217", equipment: "encaixotadora-mediseal", subgroup: "Armação de Caixas", text: "Verificação da eficiência do vácuo, funcionamento correto da armação da caixa e ponto zero mecânico com eletrônico.", level: "basic" },
  { id: "H218", equipment: "encaixotadora-mediseal", subgroup: "Empurradores", text: "Revisão do conjuto de contra-calço, guias lineares e ponto zero mecânico com eletrônico", level: "intermediate" },
  { id: "H219", equipment: "encaixotadora-mediseal", subgroup: "Esteira de saída", text: "Verificar desgates das correias e ajuste do ponto zero mecnico e eletrônico do conjunto", level: "basic" },
  { id: "H220", equipment: "encaixotadora-mediseal", subgroup: "Aplicador de fita", text: "Revisão completa do conjuto", level: "intermediate" },
  { id: "H221", equipment: "encaixotadora-mediseal", subgroup: "Aplicador de fita", text: "Realizar ajuste de pressão das molas e posicionamento das facas", level: "intermediate" },
  { id: "H222", equipment: "encaixotadora-mediseal", subgroup: "Máquina", text: "Limpeza e lubrificação Geral", level: "basic" },
];
